
services:
- docker

script:
- docker-compose up gulp-deploy

before_deploy:
  - export DEPLOY_DIR=./deploy/
  - export DEPLOY_BRANCH=gh-pages
  - rm -rf "${DEPLOY_DIR}"
  - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  - git fetch --unshallow origin "${DEPLOY_BRANCH}" 2>/dev/null  || git fetch origin
  - git worktree add -b "${DEPLOY_BRANCH}" "${DEPLOY_DIR}" origin/"${DEPLOY_BRANCH}" 2>/dev/null || git worktree add --force "${DEPLOY_DIR}" origin/"${DEPLOY_BRANCH}" 2>/dev/null
  - mkdir -p "${DEPLOY_DIR}/${TRAVIS_BRANCH}"
  - cp ./src/export/* "${DEPLOY_DIR}/${TRAVIS_BRANCH}/"

deploy:
  - provider: pages
    local-dir: ./deploy/master/
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: false
    target-branch: ${DEPLOY_BRANCH}
    verbose: true
    on:
      branch: master
  - provider: pages
    local-dir: ./deploy/
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: false
    target-branch: ${DEPLOY_BRANCH}
    verbose: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != ^gh-pages$
