gulp-server:
    #image: dduportal/md2cv:md2cv-2.0.0
    # In case of tuning, comment image line and uncomment build below
    build: ./
    volumes:
      - ./src:/app/src
    ports:
      - "4000:4000"   # Webserver port
      - "35729:35729" # Livereload port
