version: '3.3'

services:
  gulp-server:
    build: ./
    volumes:
      - ./src:/app/src
    ports:
      - "4000:4000"   # Webserver port
      - "35729:35729" # Livereload port
  
  gulp-deploy:
    build: ./
    volumes:
      - ./src:/app/src
    command: init deploy
