version: '2.4'

services:
  html:
    image: asciidoctor/docker-asciidoctor:1.1.0
    command: >
      asciidoctor /documents/index.adoc
      -a cv-url="${CV_URL}"
      -a source-url="${SOURCE_URL}"
      -a short-owner-name="${SHORT_OWNER_NAME}"
      -a toc=left
      -a toclevels=2
      -o /dist/index.html
    user: ${CURRENT_UID}
    volumes:
      - ./src:/documents
      - ./dist:/dist

  pdf:
    image: asciidoctor/docker-asciidoctor:1.1.0
    command: >
      asciidoctor-pdf /documents/index.adoc
      -a cv-url="${CV_URL}"
      -a source-url="${SOURCE_URL}"
      -a short-owner-name="${SHORT_OWNER_NAME}"
      -o /dist/cv-"${SHORT_OWNER_NAME}".pdf
    user: ${CURRENT_UID}
    volumes:
      - ./src:/documents
      - ./dist:/dist

  test:
    build: ./htmlproofer/
    command: >
      --check-html
      --http-status-ignore "999"
      --url-ignore "/localhost:/,/127.0.0.1:/"
      /dist/index.html
    user: ${CURRENT_UID}
    volumes:
      - ./dist:/dist
