# Reusable options
x-base: &cv-base
  image: asciidoctor/docker-asciidoctor:1.77.0
  user: ${CURRENT_UID}
  volumes:
    - ./src:/documents
    - ./dist:/dist

services:
  html:
    <<: *cv-base
    command: >
      asciidoctor /documents/index.adoc
      -a cv-url="${CV_URL}"
      -a source-url="${SOURCE_URL}"
      -a short-owner-name="${SHORT_OWNER_NAME}"
      -a toc=left
      -a toclevels=2
      -o /dist/index.html

  pdf:
    <<: *cv-base
    command: >
      asciidoctor-pdf /documents/index.adoc
      -a cv-url="${CV_URL}"
      -a source-url="${SOURCE_URL}"
      -a short-owner-name="${SHORT_OWNER_NAME}"
      -o /dist/cv-"${SHORT_OWNER_NAME}".pdf

  test:
    image: klakegg/html-proofer:3.19.2
    command: >
      --check-html
      --http-status-ignore "999"
      --url-ignore "/localhost:/,/127.0.0.1:/"
      /dist/index.html
    user: ${CURRENT_UID}
    volumes:
      - ./dist:/dist
